### ISSUE TITLE
Job Started Delay

### ISSUE THREAD

**Issue by nitaybz** [leofabri/hassio_appliance-status-monitor#24]
Please add option to have a delay for the Job started trigger.
Both my washing machine and dryer have random trigger when the electric consumption spike for a minute

much appreciated, and thanks for the awesome blueprint :)

**Comment by leofabri** [comment]
hey @nitaybz the feature you are referring to is already present in the latest version of the blueprint, and V3.0.0 Dev is the most complete one in terms of timers. If you have any problem, please feel free to contact me or join the discussion here https://community.home-assistant.io/t/detect-and-monitor-the-state-of-an-appliance-based-on-its-power-consumption-v2-1-1-updated
