### ISSUE TITLE
configuration.yaml Error

### ISSUE THREAD

**Issue by flo2126** [leofabri/hassio_appliance-status-monitor#27]
Hello

I got the error "invalid slug Trockner (try trockner) for dictionary value @ data['packages']"
when i copy this to the configuration.yaml

invalid slug Trockner (try trockner) for dictionary value @ data['packages']

homeassistant:
  ## Packages support enabled - Includes every .yaml file that is inside the packages/ directory
  packages: !include_dir_named packages/
  ## Warning! Please pay attention to the indentation!

Can you help me please

**Comment by flo2126** [comment]
can anybody help me please

**Comment by leofabri** [comment]
Hey @flo2126, I'm sorry for the late reply. So I've never seen such error during testing. I need to try that. I'll get back to you as soon as I discover something.

**Comment by leofabri** [comment]
It looks like it could be a problem with indentation or file naming. This is not a problem with how the packages are set up in the confifuration.yaml.

I've just noticed that Trockner is 'drier' in english, so I guess you are trying to add a custom package, is that correct?

Can you please make sure that if you have a package file called Trockner.yaml you rename it to trockner.yaml? You should avoid spaces or any other special character

**Comment by flo2126** [comment]
Hello

Thanks for your answer. The blueprint is now working. I solved the problem but forgot to close the error

**Comment by leofabri** [comment]
That's a good news. Feel free to reopen it in case you need help
